package br.edu.ifpr.paranavai.armarios.visao.curso;

import br.edu.ifpr.paranavai.armarios.controle.CursoControle;
import br.edu.ifpr.paranavai.armarios.excecoes.CursoException;
import br.edu.ifpr.paranavai.armarios.modelo.Curso;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import java.awt.Dialog;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author teren
 */
public class CriacaoEdicaoCursoUIModal extends javax.swing.JDialog {

    private Curso curso;
    private boolean estaAtualizando;
    private IndexCursoPanelUI indexCursoPanelUI;

    /**
     * Creates new form CriacaoEdicaoCursoUIModal
     */
    public CriacaoEdicaoCursoUIModal(IndexCursoPanelUI indexCursoPanelUI) {
        super((JFrame) SwingUtilities.getWindowAncestor(indexCursoPanelUI), true);
        initComponents();
        this.indexCursoPanelUI = indexCursoPanelUI;
        this.curso = new Curso();
        this.estaAtualizando = false;
        this.setTitle("Novo Curso");
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }

    public CriacaoEdicaoCursoUIModal(IndexCursoPanelUI indexCursoPanelUI, Curso curso) {
        this(indexCursoPanelUI);
        this.curso = curso;
        this.estaAtualizando = true;

        initTextFields();
    }

    private void initTextFields() {
        String titulo = "Edição do Curso ";
        lblTitulo.setText(titulo + this.curso.getId());
        this.setTitle(titulo + this.curso.getId());
        txtNomeCurso.setText(this.curso.getNome());
        ckbAtivo.setSelected(this.curso.isAtivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        lblNomeCurso = new javax.swing.JLabel();
        lblAtivo = new javax.swing.JLabel();
        ckbAtivo = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(394, 290));
        setModal(true);
        setName("dialogo"); // NOI18N
        setPreferredSize(new java.awt.Dimension(394, 290));
        setResizable(false);
        setSize(new java.awt.Dimension(394, 290));

        panelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        panelGeral.setMinimumSize(new java.awt.Dimension(394, 237));
        panelGeral.setRequestFocusEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Novo Curso");

        lblNomeCurso.setText("Nome do Curso *:");

        lblAtivo.setText("Ativo?");

        ckbAtivo.setSelected(true);
        ckbAtivo.setText("Sim!");
        ckbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbAtivoItemStateChanged(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(txtNomeCurso)
                            .addComponent(lblNomeCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSalvar)
                        .addGap(78, 78, 78)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblNomeCurso)
                .addGap(5, 5, 5)
                .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblAtivo)
                .addGap(5, 5, 5)
                .addComponent(ckbAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelGeral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbAtivoItemStateChanged
        ckbAtivo.setText((evt.getStateChange() == 1 ? "Sim!" : "Não!"));
    }//GEN-LAST:event_ckbAtivoItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.curso.setNome(txtNomeCurso.getText());
        this.curso.setAtivo(ckbAtivo.isSelected());

        if (estaAtualizando)
            atualizar();
        else
            salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void salvar() throws HeadlessException {
        try {
            CursoControle.inserir(curso);
            JOptionPane.showMessageDialog(this, MensagemUtil.CURSO_INSERCAO_SUCESSO);
            fecharFormulario();
        } catch (CursoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.CURSO_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizar() {
        try {
            CursoControle.atualizar(curso);
            JOptionPane.showMessageDialog(this, MensagemUtil.CURSO_ATUALIZACAO_SUCESSO);
            fecharFormulario();
        } catch (CursoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.CURSO_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fecharFormulario() {
        this.dispose();
        this.indexCursoPanelUI.init();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckbAtivo;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JTextField txtNomeCurso;
    // End of variables declaration//GEN-END:variables
}
