/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.visao.localizacao;


import br.edu.ifpr.paranavai.armarios.excecoes.LocalizacaoException;

import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import br.edu.ifpr.paranavai.armarios.servico.LocalizacaoServico;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor Marcelo Figueiredo Terenciani
 */
public class CriacaoEdicaoLocalizacaoUIModal extends javax.swing.JDialog {

    private Localizacao localizacao;
    private boolean estaAtualizando;
    private IndexLocalizacaoUI indexLocalizacaoUI;
    /**
     * Creates new form CriacaoEdicaoLocalizacaoUIModal
     */
    
    public CriacaoEdicaoLocalizacaoUIModal(IndexLocalizacaoUI indexLocalizacaoUI) {
        super(indexLocalizacaoUI, true);
        initComponents();
        this.indexLocalizacaoUI = indexLocalizacaoUI;
        this.localizacao = new Localizacao();
        this.estaAtualizando = false;
        this.setTitle("Nova localização de armários");
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }

    public CriacaoEdicaoLocalizacaoUIModal(IndexLocalizacaoUI indexLocalizacaoUI, Localizacao localizacao, boolean estaAtualizando) {
        super(indexLocalizacaoUI, true);
        initComponents();
        this.localizacao = localizacao;
        this.indexLocalizacaoUI = indexLocalizacaoUI;
        this.estaAtualizando = estaAtualizando;

        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        
        String titulo = estaAtualizando ? "Edição da localização " : "Dados da localização ";
        
        lblTitulo.setText(titulo + localizacao.getId());
        this.setTitle(titulo + localizacao.getId());
        txtNomeLocalizacao.setText(localizacao.getDescricao());
        ckbAtivo.setSelected(localizacao.isAtivo());
        
        if(!estaAtualizando)
            desabilitarComponentes();
    }

    private void desabilitarComponentes() {
        btnCancelar.setVisible(false);
        btnSalvar.setVisible(false);
        panelGeral.setEnabled(false);
        txtNomeLocalizacao.setEnabled(false);
        txtNomeLocalizacao.setDisabledTextColor(Color.BLACK);
        ckbAtivo.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        txtNomeLocalizacao = new javax.swing.JTextField();
        lblNomeCurso = new javax.swing.JLabel();
        lblAtivo = new javax.swing.JLabel();
        ckbAtivo = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(394, 290));
        setModal(true);
        setName("dialogo"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(394, 290));

        panelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        panelGeral.setMinimumSize(new java.awt.Dimension(394, 237));
        panelGeral.setRequestFocusEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Nova localização de armários");

        lblNomeCurso.setText("Nome da localização *:");

        lblAtivo.setText("Ativo?");

        ckbAtivo.setSelected(true);
        ckbAtivo.setText("Sim!");
        ckbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbAtivoItemStateChanged(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .addComponent(txtNomeLocalizacao)
                            .addComponent(lblNomeCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ckbAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnSalvar)
                        .addGap(78, 78, 78)
                        .addComponent(btnCancelar)))
                .addGap(20, 20, 20))
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblNomeCurso)
                .addGap(5, 5, 5)
                .addComponent(txtNomeLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lblAtivo)
                .addGap(5, 5, 5)
                .addComponent(ckbAtivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelGeral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ckbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbAtivoItemStateChanged
        ckbAtivo.setText((evt.getStateChange() == 1 ? "Sim!" : "Não!"));
    }//GEN-LAST:event_ckbAtivoItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        this.localizacao.setDescricao(txtNomeLocalizacao.getText());
        this.localizacao.setAtivo(ckbAtivo.isSelected());

        if (estaAtualizando)
        atualizar();
        else
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

        private void salvar() throws HeadlessException {
        try {
            LocalizacaoServico.inserir(localizacao);
            JOptionPane.showMessageDialog(this, MensagemUtil.LOCALIZACAO_INSERCAO_SUCESSO);
            fecharFormulario();
        //} catch (LocalizacaoException e) {
        //    JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.LOCALIZACAO_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizar() {
        try {
            LocalizacaoServico.atualizar(localizacao);
            JOptionPane.showMessageDialog(this, MensagemUtil.LOCALIZACAO_ATUALIZACAO_SUCESSO);
            fecharFormulario();
        //} catch (LocalizacaoException e) {
        //    JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.LOCALIZACAO_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void fecharFormulario(){
        this.dispose();
        this.indexLocalizacaoUI.init();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckbAtivo;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JTextField txtNomeLocalizacao;
    // End of variables declaration//GEN-END:variables
}
