package br.edu.ifpr.paranavai.armarios.visao.localizacao;

import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import br.edu.ifpr.paranavai.armarios.servico.LocalizacaoServico;
import br.edu.ifpr.paranavai.armarios.visao.tabela.acoes.AcoesEventoTabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author professor Marcelo F. Terenciani
 */
public class IndexLocalizacaoPanelUI extends javax.swing.JPanel {
    private final int QUANTIDADE_COLUNAS = 4;
    private List<Localizacao> listaDeLocalizacoes;

    public IndexLocalizacaoPanelUI() {
        initComponents();
        init();
    }

    public void init() {
        listaDeLocalizacoes = LocalizacaoServico.buscarTodos();
        populaTabela(listaDeLocalizacoes);
    }

    private void populaTabela(List<Localizacao> lista) {
        AcoesEventoTabela evento = new AcoesEventoTabelaLocalizacao();

        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) tblLocalizacao.getModel();
        tblLocalizacao.getColumnModel().getColumn(QUANTIDADE_COLUNAS - 1).setCellRenderer(new RenderizadorDasAcoesDaCelulaLocalizacao());
        tblLocalizacao.getColumnModel().getColumn(QUANTIDADE_COLUNAS - 1).setCellEditor(new EditorDasAcoesDaCelulaLocalizacao(evento));
        //  Primeiro limpa a tabela
        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }

        for (int i = 0; i < lista.size(); i++) {
            Localizacao mostraLocalizacao = lista.get(i);
            Object[] dadosLinha = new Object[QUANTIDADE_COLUNAS];
            dadosLinha[0] = mostraLocalizacao.getId();
            dadosLinha[1] = mostraLocalizacao.getDescricao();
            dadosLinha[2] = mostraLocalizacao.isAtivo() ? "Ativo" : "Inativo";

            modeloDeColunasDaTabela.addRow(dadosLinha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelSuperior = new javax.swing.JPanel();
        panelBusca = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocalizacao = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(4, 4));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.GridLayout(1, 0));

        painelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        painelGeral.setLayout(new java.awt.BorderLayout(0, 5));

        painelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelSuperior.setLayout(new java.awt.GridLayout(2, 0));

        panelBusca.setBackground(new java.awt.Color(255, 255, 255));
        panelBusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        panelBusca.setLayout(new javax.swing.BoxLayout(panelBusca, javax.swing.BoxLayout.LINE_AXIS));

        lblBusca.setText("Descrição: ");
        lblBusca.setMaximumSize(new java.awt.Dimension(70, 16));
        lblBusca.setMinimumSize(new java.awt.Dimension(70, 16));
        lblBusca.setPreferredSize(new java.awt.Dimension(70, 16));
        panelBusca.add(lblBusca);

        txtBusca.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        panelBusca.add(txtBusca);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusca.add(btnBuscar);

        painelSuperior.add(panelBusca);

        panelNovo.setBackground(new java.awt.Color(255, 255, 255));
        panelNovo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelNovo.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        btnNovo.setText("Novo");
        btnNovo.setMaximumSize(new java.awt.Dimension(72, 72));
        btnNovo.setMinimumSize(new java.awt.Dimension(72, 72));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelNovo.add(btnNovo);

        painelSuperior.add(panelNovo);

        painelGeral.add(painelSuperior, java.awt.BorderLayout.PAGE_START);

        painelInferior.setBackground(new java.awt.Color(0, 153, 0));
        painelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelInferior.setLayout(new java.awt.BorderLayout());

        tblLocalizacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Descrição", "Ativo", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLocalizacao.setRowHeight(30);
        tblLocalizacao.setSelectionBackground(new java.awt.Color(57, 137, 111));
        tblLocalizacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblLocalizacao);

        painelInferior.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        painelGeral.add(painelInferior, java.awt.BorderLayout.CENTER);

        add(painelGeral);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ArrayList<Localizacao> filtrado = new ArrayList<>();
        for (Localizacao localizacao : listaDeLocalizacoes) {
            if (localizacao.getDescricao().toUpperCase().contains(txtBusca.getText().toUpperCase())) {
                filtrado.add(localizacao);
            }
        }
        populaTabela(filtrado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CriacaoEdicaoLocalizacaoUIModal criacaoEdicaoLocalizacao = new CriacaoEdicaoLocalizacaoUIModal(this);
        criacaoEdicaoLocalizacao.setLocationRelativeTo(this);
        criacaoEdicaoLocalizacao.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelNovo;
    private javax.swing.JTable tblLocalizacao;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
