package br.edu.ifpr.paranavai.armarios.visao.estudante;

import br.edu.ifpr.paranavai.armarios.controle.EstudanteControle;
import br.edu.ifpr.paranavai.armarios.excecoes.EstudanteException;
import br.edu.ifpr.paranavai.armarios.modelo.Curso;
import br.edu.ifpr.paranavai.armarios.modelo.Estudante;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import java.awt.Dialog;
import java.awt.HeadlessException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author professor Marcelo F. Terenciani
 */
public class CriacaoEdicaoEstudanteUIModal extends javax.swing.JDialog {

    private Estudante estudante;
    private boolean estaAtualizando;
    private IndexEstudanteUI indexEstudanteUI;
    private CursoComboBoxModel cursoComboBoxModel;
     
    public CriacaoEdicaoEstudanteUIModal(IndexEstudanteUI indexEstudanteUI) {
        super(indexEstudanteUI, true);
        initComponents();
        this.indexEstudanteUI = indexEstudanteUI;
        this.estudante = new Estudante();
        this.estaAtualizando = false;
        
        this.cursoComboBoxModel = EstudanteControle.inicializaComboBoxCurso();
        cbxCursoEstudante.setModel(cursoComboBoxModel);
        
        this.setTitle("Novo Estudante");
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }

    public CriacaoEdicaoEstudanteUIModal(IndexEstudanteUI indexEstudanteUI, Estudante estudante) {
        super(indexEstudanteUI, true);
        initComponents();
        this.estudante = estudante;
        this.indexEstudanteUI = indexEstudanteUI;
        this.estaAtualizando = true;
        this.cursoComboBoxModel = EstudanteControle.inicializaComboBoxCurso();
        cbxCursoEstudante.setModel(cursoComboBoxModel);

        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
                
        lblTitulo.setText("Edição do Estudante " + estudante.getId());
        this.setTitle("Edição do Estudante " + estudante.getId());
        txtNomeEstudante.setText(estudante.getNome());
        txtSobrenomeEstudante.setText(estudante.getSobrenome());
        txtRaEstudante.setText(estudante.getRa());
        txtTelefoneEstudante.setText(estudante.getTelefone());
        txtEmailEstudante.setText(estudante.getEmail());
        cbxCursoEstudante.setSelectedItem(estudante.getCurso());
        txtSenhaEstudante.setText(estudante.getSenha());
        txtConfirmaSenhaEstudante.setText(estudante.getSenha());
        this.estudante.setAtivo(ckbAtivo.isSelected());
        ckbAtivo.setSelected(estudante.isAtivo());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNomeEstudante = new javax.swing.JLabel();
        txtNomeEstudante = new javax.swing.JTextField();
        lblSobrenomeEstudante = new javax.swing.JLabel();
        txtSobrenomeEstudante = new javax.swing.JTextField();
        lblRaEstudante = new javax.swing.JLabel();
        txtRaEstudante = new javax.swing.JTextField();
        lblTelefoneEstudante = new javax.swing.JLabel();
        txtTelefoneEstudante = new javax.swing.JTextField();
        lblEmailEstudante = new javax.swing.JLabel();
        txtEmailEstudante = new javax.swing.JTextField();
        lblCursoEstudante = new javax.swing.JLabel();
        cbxCursoEstudante = new javax.swing.JComboBox<>();
        lblSenhaEstudante = new javax.swing.JLabel();
        txtSenhaEstudante = new javax.swing.JPasswordField();
        lblConfirmaSenhaEstudante = new javax.swing.JLabel();
        txtConfirmaSenhaEstudante = new javax.swing.JPasswordField();
        lblAtivo = new javax.swing.JLabel();
        ckbAtivo = new javax.swing.JCheckBox();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estudante");
        setMinimumSize(new java.awt.Dimension(394, 290));
        setModal(true);
        setName("dialogo"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(394, 290));

        panelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        panelGeral.setMinimumSize(new java.awt.Dimension(394, 237));
        panelGeral.setRequestFocusEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Novo Estudante");

        lblNomeEstudante.setText("Nome*:");

        lblSobrenomeEstudante.setText("Sobrenome*:");

        lblRaEstudante.setText("Matrícula (RA)*:");

        lblTelefoneEstudante.setText("Telefone*:");

        lblEmailEstudante.setText("E-mail*:");

        lblCursoEstudante.setText("Curso*:");

        cbxCursoEstudante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSenhaEstudante.setText("Senha*:");

        txtSenhaEstudante.setText("jPasswordField2");

        lblConfirmaSenhaEstudante.setText("Confirmação de Senha*:");

        txtConfirmaSenhaEstudante.setText("jPasswordField1");

        lblAtivo.setText("Ativo?");

        ckbAtivo.setSelected(true);
        ckbAtivo.setText("Sim!");
        ckbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbAtivoItemStateChanged(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(btnSalvar)
                        .addGap(134, 134, 134)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtTelefoneEstudante)
                                    .addComponent(lblTelefoneEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmailEstudante)
                                    .addComponent(lblEmailEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblCursoEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxCursoEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNomeEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(lblNomeEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSobrenomeEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtSobrenomeEstudante))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRaEstudante)
                                    .addComponent(lblRaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeralLayout.createSequentialGroup()
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSenhaEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtSenhaEstudante))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblConfirmaSenhaEstudante, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtConfirmaSenhaEstudante))
                                .addGap(18, 18, 18)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckbAtivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(20, 20, 20))))
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblNomeEstudante)
                        .addGap(5, 5, 5)
                        .addComponent(txtNomeEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addComponent(lblSobrenomeEstudante)
                        .addGap(5, 5, 5)
                        .addComponent(txtSobrenomeEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addComponent(lblRaEstudante)
                        .addGap(5, 5, 5)
                        .addComponent(txtRaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTelefoneEstudante)
                        .addGap(5, 5, 5)
                        .addComponent(txtTelefoneEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(cbxCursoEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCursoEstudante)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addComponent(lblEmailEstudante)
                                .addGap(5, 5, 5)
                                .addComponent(txtEmailEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblSenhaEstudante)
                        .addGap(5, 5, 5)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmaSenhaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenhaEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConfirmaSenhaEstudante)
                            .addComponent(lblAtivo))
                        .addGap(6, 6, 6)
                        .addComponent(ckbAtivo)))
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(20, 20, 20))
        );

        getContentPane().add(panelGeral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Curso curso = (Curso)cbxCursoEstudante.getSelectedItem();
        this.estudante.setNome(txtNomeEstudante.getText());
        this.estudante.setSobrenome(txtSobrenomeEstudante.getText());
        this.estudante.setRa(txtRaEstudante.getText());
        this.estudante.setTelefone(txtTelefoneEstudante.getText());
        this.estudante.setEmail(txtEmailEstudante.getText());
        this.estudante.setCurso(curso);
        this.estudante.setSenha(Arrays.toString(txtSenhaEstudante.getPassword()));
        
        this.estudante.setAtivo(ckbAtivo.isSelected());
            
        if (estaAtualizando)
        atualizar();
        else
        salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ckbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbAtivoItemStateChanged
        ckbAtivo.setText((evt.getStateChange() == 1 ? "Sim!" : "Não!"));
    }//GEN-LAST:event_ckbAtivoItemStateChanged

        private void salvar() throws HeadlessException {
        try {
            EstudanteControle.inserir(estudante);
            JOptionPane.showMessageDialog(this, MensagemUtil.ESTUDANTE_INSERCAO_SUCESSO);
            fecharFormulario();
        } catch (EstudanteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.ESTUDANTE_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizar() {
        try {
            EstudanteControle.atualizar(estudante);
            JOptionPane.showMessageDialog(this, MensagemUtil.ESTUDANTE_ATUALIZACAO_SUCESSO);
            fecharFormulario();
        } catch (EstudanteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, MensagemUtil.ESTUDANTE_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL , JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void fecharFormulario(){
        this.dispose();
        this.indexEstudanteUI.init();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbxCursoEstudante;
    private javax.swing.JCheckBox ckbAtivo;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblConfirmaSenhaEstudante;
    private javax.swing.JLabel lblCursoEstudante;
    private javax.swing.JLabel lblEmailEstudante;
    private javax.swing.JLabel lblNomeEstudante;
    private javax.swing.JLabel lblRaEstudante;
    private javax.swing.JLabel lblSenhaEstudante;
    private javax.swing.JLabel lblSobrenomeEstudante;
    private javax.swing.JLabel lblTelefoneEstudante;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JPasswordField txtConfirmaSenhaEstudante;
    private javax.swing.JTextField txtEmailEstudante;
    private javax.swing.JTextField txtNomeEstudante;
    private javax.swing.JTextField txtRaEstudante;
    private javax.swing.JPasswordField txtSenhaEstudante;
    private javax.swing.JTextField txtSobrenomeEstudante;
    private javax.swing.JTextField txtTelefoneEstudante;
    // End of variables declaration//GEN-END:variables
}
