package br.edu.ifpr.paranavai.armarios.visao.estudante;

import br.edu.ifpr.paranavai.armarios.excecoes.ArmarioException;
import br.edu.ifpr.paranavai.armarios.excecoes.EmprestimoException;
import br.edu.ifpr.paranavai.armarios.modelo.Armario;
import br.edu.ifpr.paranavai.armarios.modelo.Emprestimo;
import br.edu.ifpr.paranavai.armarios.modelo.Estudante;
import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import br.edu.ifpr.paranavai.armarios.modelo.StatusArmario;
import br.edu.ifpr.paranavai.armarios.servico.ArmarioServico;
import br.edu.ifpr.paranavai.armarios.servico.ComboBoxServico;
import br.edu.ifpr.paranavai.armarios.servico.EmprestimoServico;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import br.edu.ifpr.paranavai.armarios.visao.EmprestimoEstudanteUI;
import br.edu.ifpr.paranavai.armarios.visao.combobox.ArmarioComboBoxModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Allan Fernando O de Andrade
 */
public class EstudantesEmprestimoUI extends javax.swing.JDialog {

    private EmprestimoEstudanteUI emprestimoEstudanteUI;
    private Localizacao localizacao;
    private Armario armarioEscolhido;
    private Estudante estudante;

    /**
     * Creates new form EstudanteEmprestimoDialog
     *
     * @param emprestimoEstudanteUI
     * @param estudante
     * @param localizacao
     */
    public EstudantesEmprestimoUI(EmprestimoEstudanteUI emprestimoEstudanteUI, Estudante estudante, Localizacao localizacao) {
        super((JFrame) SwingUtilities.getWindowAncestor(emprestimoEstudanteUI), true);
        initComponents();
        this.estudante = estudante;
        this.localizacao = localizacao;
        ArmarioComboBoxModel armarioComboBoxModel = ComboBoxServico.inicializaComboBoxArmarioAtivo(localizacao);
        cbxArmario.setModel(armarioComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConteudo = new javax.swing.JPanel();
        painelEmprestimo = new javax.swing.JPanel();
        lblArmario = new javax.swing.JLabel();
        cbxArmario = new javax.swing.JComboBox<>();
        btnConfirmarEmprestimo = new javax.swing.JToggleButton();
        btnSair = new javax.swing.JToggleButton();
        campoResposta = new javax.swing.JLabel();
        lblIconeIFPR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Definir Localização");

        painelConteudo.setBackground(new java.awt.Color(0, 153, 0));
        painelConteudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        painelConteudo.setLayout(new java.awt.BorderLayout());

        painelEmprestimo.setBackground(new java.awt.Color(255, 255, 255));
        painelEmprestimo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empréstimo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12))); // NOI18N

        lblArmario.setBackground(new java.awt.Color(255, 255, 255));
        lblArmario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblArmario.setText("Selecione o armário:");

        cbxArmario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxArmario.setMaximumRowCount(10);

        btnConfirmarEmprestimo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnConfirmarEmprestimo.setText("Emprestar");
        btnConfirmarEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEmprestimoActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        campoResposta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout painelEmprestimoLayout = new javax.swing.GroupLayout(painelEmprestimo);
        painelEmprestimo.setLayout(painelEmprestimoLayout);
        painelEmprestimoLayout.setHorizontalGroup(
            painelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfirmarEmprestimo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cbxArmario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblArmario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
            .addComponent(campoResposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelEmprestimoLayout.setVerticalGroup(
            painelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmprestimoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArmario)
                .addGap(3, 3, 3)
                .addComponent(cbxArmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmarEmprestimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(campoResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelConteudo.add(painelEmprestimo, java.awt.BorderLayout.CENTER);

        lblIconeIFPR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeIFPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iflogomenor.png"))); // NOI18N
        painelConteudo.add(lblIconeIFPR, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEmprestimoActionPerformed
        if (armarioEscolhido == null) {
            campoResposta.setText(MensagemUtil.ARMARIO_ESCOLHA_UM);
        } else {
            Emprestimo emprestimo = new Emprestimo();
            emprestimo.setArmario(armarioEscolhido);
            emprestimo.setEstudante(estudante);

            int resposta = JOptionPane.showConfirmDialog(null, MensagemUtil.EMPRESTIMO_CONFIRMA_EMPRESTIMO + " do armário " + armarioEscolhido.getNumero() + " na/no " + localizacao.getDescricao() + "?", "Confirmação", JOptionPane.OK_CANCEL_OPTION);

            if (resposta == JOptionPane.OK_OPTION) {
                try {
                    EmprestimoServico.inserir(emprestimo);
                    armarioEscolhido.setStatus(StatusArmario.OCUPADO);
                    try {
                        ArmarioServico.atualizar(armarioEscolhido);
                    } catch (ArmarioException ex) {
                        Logger.getLogger(EstudantesEmprestimoUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    fecharFormulario();
                } catch (EmprestimoException ex) {
                    Logger.getLogger(EstudantesEmprestimoUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnConfirmarEmprestimoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_btnSairActionPerformed

    private void fecharFormulario() {
        this.dispose();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnConfirmarEmprestimo;
    private javax.swing.JToggleButton btnSair;
    private javax.swing.JLabel campoResposta;
    private javax.swing.JComboBox<String> cbxArmario;
    private javax.swing.JLabel lblArmario;
    private javax.swing.JLabel lblIconeIFPR;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelEmprestimo;
    // End of variables declaration//GEN-END:variables
}
