package br.edu.ifpr.paranavai.armarios.visao.servidor;

import br.edu.ifpr.paranavai.armarios.excecoes.ServidorException;
import br.edu.ifpr.paranavai.armarios.modelo.Servidor;
import br.edu.ifpr.paranavai.armarios.servico.ServidorServico;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import br.edu.ifpr.paranavai.armarios.utils.OperacaoUtil;
import java.awt.Dialog;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.util.Arrays;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author professor Marcelo F. Terenciani
 */
public class CriacaoEdicaoServidorUIModal extends javax.swing.JDialog {

    private Servidor estudante;
    private boolean estaAtualizando;
    private IndexServidorPanelUI indexServidorPanelUI;
    private MaskFormatter maskFormatter;

    public CriacaoEdicaoServidorUIModal(IndexServidorPanelUI indexServidorPanelUI) {
        super((JFrame) SwingUtilities.getWindowAncestor(indexServidorPanelUI), true);

        try {
            this.maskFormatter = new MaskFormatter("(##) # ####-####");
            this.maskFormatter.setPlaceholderCharacter('_');
        } catch (ParseException e) {
            e.printStackTrace();
        }

        initComponents();
        this.indexServidorPanelUI = indexServidorPanelUI;
        this.estudante = new Servidor();
        this.estaAtualizando = false;

        this.setTitle("Novo Servidor");
        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }

    public CriacaoEdicaoServidorUIModal(IndexServidorPanelUI indexServidorPanelUI, Servidor estudante) {
        this(indexServidorPanelUI);
        this.estudante = estudante;
        this.estaAtualizando = true;

        initTextFields(estudante);
    }

    private void initTextFields(Servidor estudante1) {
        lblTitulo.setText("Edição do Servidor " + estudante1.getId());
        this.setTitle("Edição do Servidor " + estudante1.getId());
        txtNome.setText(estudante1.getNome());
        txtSobrenome.setText(estudante1.getSobrenome());
        txtSiape.setText(estudante1.getSiape());
        txtTelefone.setText(estudante1.getTelefone());
        txtEmail.setText(estudante1.getEmail());
        txtSenha.setText(estudante1.getSenha());
        txtConfirmaSenha.setText(estudante1.getSenha());
        this.estudante.setAtivo(ckbAtivo.isSelected());
        ckbAtivo.setSelected(estudante1.isAtivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeral = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblSobrenome = new javax.swing.JLabel();
        txtSobrenome = new javax.swing.JTextField();
        lblSiape = new javax.swing.JLabel();
        txtSiape = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new JFormattedTextField(this.maskFormatter);
        lblTelefoneInvalido = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmailInvalido = new javax.swing.JLabel();
        lblAtivo = new javax.swing.JLabel();
        ckbAtivo = new javax.swing.JCheckBox();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblConfirmaSenha = new javax.swing.JLabel();
        txtConfirmaSenha = new javax.swing.JPasswordField();
        lblSenhaInvalida = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidor");
        setMinimumSize(new java.awt.Dimension(394, 290));
        setModal(true);
        setName("dialogo"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(394, 290));

        panelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        panelGeral.setMinimumSize(new java.awt.Dimension(394, 237));
        panelGeral.setRequestFocusEnabled(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Novo Servidor");

        lblNome.setText("Nome*:");

        lblSobrenome.setText("Sobrenome*:");

        lblSiape.setText("SIAPE*:");

        lblTelefone.setText("Telefone*:");

        txtTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefoneFocusLost(evt);
            }
        });

        lblTelefoneInvalido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblTelefoneInvalido.setForeground(new java.awt.Color(255, 51, 51));
        lblTelefoneInvalido.setMaximumSize(new java.awt.Dimension(30, 20));
        lblTelefoneInvalido.setMinimumSize(new java.awt.Dimension(30, 20));
        lblTelefoneInvalido.setPreferredSize(new java.awt.Dimension(30, 20));
        lblTelefoneInvalido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblEmail.setText("E-mail*:");

        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });

        lblEmailInvalido.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblEmailInvalido.setForeground(new java.awt.Color(255, 51, 51));
        lblEmailInvalido.setMaximumSize(new java.awt.Dimension(24, 20));
        lblEmailInvalido.setMinimumSize(new java.awt.Dimension(24, 20));
        lblEmailInvalido.setPreferredSize(new java.awt.Dimension(24, 20));
        lblEmailInvalido.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblAtivo.setText("Ativo?");

        ckbAtivo.setSelected(true);
        ckbAtivo.setText("Sim!");
        ckbAtivo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ckbAtivoItemStateChanged(evt);
            }
        });

        lblSenha.setText("Senha*:");

        txtSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSenhaKeyReleased(evt);
            }
        });

        lblConfirmaSenha.setText("Confirmação de Senha*:");

        txtConfirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConfirmaSenhaKeyReleased(evt);
            }
        });

        lblSenhaInvalida.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblSenhaInvalida.setForeground(new java.awt.Color(255, 51, 51));
        lblSenhaInvalida.setMaximumSize(new java.awt.Dimension(30, 20));
        lblSenhaInvalida.setMinimumSize(new java.awt.Dimension(30, 20));
        lblSenhaInvalida.setPreferredSize(new java.awt.Dimension(30, 20));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSobrenome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(lblTelefoneInvalido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(txtTelefone))
                                .addGap(20, 20, 20)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmailInvalido, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblSiape, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelGeralLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ckbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeralLayout.createSequentialGroup()
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblSenhaInvalida, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGeralLayout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(btnSalvar)
                                .addGap(134, 134, 134)
                                .addComponent(btnCancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addGap(5, 5, 5)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addComponent(lblSobrenome)
                        .addGap(5, 5, 5)
                        .addComponent(txtSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeralLayout.createSequentialGroup()
                        .addComponent(lblSiape)
                        .addGap(5, 5, 5)
                        .addComponent(txtSiape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefone)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(lblAtivo))
                        .addGap(5, 5, 5)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbAtivo))))
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailInvalido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneInvalido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGeralLayout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addGap(5, 5, 5)
                        .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblConfirmaSenha))
                .addGap(0, 0, 0)
                .addComponent(lblSenhaInvalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addGap(20, 20, 20))
        );

        lblEmailInvalido.getAccessibleContext().setAccessibleName("lblEmailInvalido");

        getContentPane().add(panelGeral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if (!Arrays.equals(txtConfirmaSenha.getPassword(), txtSenha.getPassword())) {
            JOptionPane.showMessageDialog(this, MensagemUtil.SENHAS_NAO_CONFEREM);
            return;
        }

        this.estudante.setNome(txtNome.getText());
        this.estudante.setSobrenome(txtSobrenome.getText());
        this.estudante.setSiape(txtSiape.getText());
        this.estudante.setTelefone(txtTelefone.getText());
        this.estudante.setEmail(txtEmail.getText());
        this.estudante.setAtivo(ckbAtivo.isSelected());

        char[] caracteresSenha = this.txtSenha.getPassword();
        String senha = new String(caracteresSenha);
        if (!senha.equals(this.estudante.getSenha())) {
            this.estudante.setSenha(senha);
        }

        if (estaAtualizando)
            atualizar();
        else
            salvar();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void ckbAtivoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ckbAtivoItemStateChanged
        ckbAtivo.setText((evt.getStateChange() == 1 ? "Sim!" : "Não!"));
    }//GEN-LAST:event_ckbAtivoItemStateChanged

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if (OperacaoUtil.ehEmailValido(this.txtEmail.getText()))
            lblEmailInvalido.setText("");
        else
            lblEmailInvalido.setText(MensagemUtil.EMAIL_INVALIDO);
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSenhaKeyReleased
        if (Arrays.equals(txtConfirmaSenha.getPassword(), txtSenha.getPassword())) {
            lblSenhaInvalida.setText("");
        } else {
            lblSenhaInvalida.setText(MensagemUtil.SENHAS_NAO_CONFEREM);
        }
    }//GEN-LAST:event_txtSenhaKeyReleased

    private void txtConfirmaSenhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConfirmaSenhaKeyReleased
        if (Arrays.equals(txtConfirmaSenha.getPassword(), txtSenha.getPassword())) {
            lblSenhaInvalida.setText("");
        } else {
            lblSenhaInvalida.setText(MensagemUtil.SENHAS_NAO_CONFEREM);
        }
    }//GEN-LAST:event_txtConfirmaSenhaKeyReleased

    private void txtTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefoneFocusLost
        if (OperacaoUtil.ehTelefoneValido(this.txtTelefone.getText())) {
            lblTelefoneInvalido.setText("");
        } else {
            lblTelefoneInvalido.setText(MensagemUtil.TELEFONE_INVALIDO);
        }

    }//GEN-LAST:event_txtTelefoneFocusLost

    private void salvar() throws HeadlessException {
        try {
            ServidorServico.inserir(estudante);
            JOptionPane.showMessageDialog(this, MensagemUtil.SERVIDOR_INSERCAO_SUCESSO);
            fecharFormulario();
        } catch (ServidorException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, MensagemUtil.SERVIDOR_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void atualizar() {
        try {
            ServidorServico.atualizar(estudante);
            JOptionPane.showMessageDialog(this, MensagemUtil.SERVIDOR_ATUALIZACAO_SUCESSO);
            fecharFormulario();
        } catch (ServidorException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, MensagemUtil.SERVIDOR_INSERCAO_ERRO_PADRAO, MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        }
    }

    private void fecharFormulario() {
        this.indexServidorPanelUI.init();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox ckbAtivo;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailInvalido;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaInvalida;
    private javax.swing.JLabel lblSiape;
    private javax.swing.JLabel lblSobrenome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTelefoneInvalido;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JPasswordField txtConfirmaSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtSiape;
    private javax.swing.JTextField txtSobrenome;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
