package br.edu.ifpr.paranavai.armarios.visao.concessao;

import br.edu.ifpr.paranavai.armarios.excecoes.ConcessaoException;
import br.edu.ifpr.paranavai.armarios.modelo.Armario;
import br.edu.ifpr.paranavai.armarios.modelo.Concessao;
import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import br.edu.ifpr.paranavai.armarios.modelo.Servidor;
import br.edu.ifpr.paranavai.armarios.modelo.StatusArmario;
import br.edu.ifpr.paranavai.armarios.servico.ArmarioServico;
import br.edu.ifpr.paranavai.armarios.servico.ComboBoxServico;
import br.edu.ifpr.paranavai.armarios.servico.ConcessaoServico;
import br.edu.ifpr.paranavai.armarios.servico.ServidorServico;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import br.edu.ifpr.paranavai.armarios.visao.combobox.ArmarioComboBoxModel;
import br.edu.ifpr.paranavai.armarios.visao.combobox.EstudanteComboBoxModel;
import br.edu.ifpr.paranavai.armarios.visao.combobox.LocalizacaoComboBoxModel;
import java.awt.Dialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author professor Marcelo F. Terenciani
 */
public class ConcessaoUIModal extends javax.swing.JDialog {

    private Concessao concessao;
    private IndexConcessaoPanelUI indexConcessaoPanelUI;

    Servidor servidor = ServidorServico.buscarUnicoPorEmailOuSiape(System.getProperty("user"));

    public ConcessaoUIModal(IndexConcessaoPanelUI indexConcessaoPanelUI) {
        super((JFrame) SwingUtilities.getWindowAncestor(indexConcessaoPanelUI), true);
     
        initComponents();
        this.indexConcessaoPanelUI = indexConcessaoPanelUI;

        this.concessao = new Concessao();

        LocalizacaoComboBoxModel localizacaoComboBoxModel = ComboBoxServico.inicializaComboBoxLocalizacao();

        cbxLocalizacaoArmarioConcessao.setModel(localizacaoComboBoxModel);

        this.setModalExclusionType(Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        panelGeral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelConcessao = new javax.swing.JPanel();
        cbxLocalizacaoArmarioConcessao = new javax.swing.JComboBox<>();
        cbxArmarioConcessao = new javax.swing.JComboBox<>();
        lblLocalizacaoArmario1 = new javax.swing.JLabel();
        lblArmario1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacoes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        externoRadio = new javax.swing.JRadioButton();
        salvarConcessao = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Servidor");
        setMinimumSize(new java.awt.Dimension(394, 290));
        setModal(true);
        setName("dialogo"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(394, 290));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelGeral.setBackground(new java.awt.Color(0, 153, 0));
        panelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        panelGeral.setMaximumSize(new java.awt.Dimension(300, 2147483647));
        panelGeral.setMinimumSize(new java.awt.Dimension(299, 237));
        panelGeral.setPreferredSize(new java.awt.Dimension(300, 430));
        panelGeral.setRequestFocusEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/IfLogo_dark.png"))); // NOI18N

        panelConcessao.setBackground(new java.awt.Color(255, 255, 255));
        panelConcessao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Concessão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        cbxLocalizacaoArmarioConcessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxLocalizacaoArmarioConcessaoActionPerformed(evt);
            }
        });

        cbxArmarioConcessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxArmarioConcessaoActionPerformed(evt);
            }
        });

        lblLocalizacaoArmario1.setText("Localização do Armário*:");

        lblArmario1.setText("Armario*:");

        informacoes.setColumns(20);
        informacoes.setLineWrap(true);
        informacoes.setRows(5);
        informacoes.setText("Utilização do servidor.");
        informacoes.setMaximumSize(new java.awt.Dimension(232, 2147483647));
        jScrollPane1.setViewportView(informacoes);

        jLabel3.setText("Informações:");

        externoRadio.setText("Para pessoa externa");
        externoRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externoRadioActionPerformed(evt);
            }
        });

        salvarConcessao.setText("Salvar");
        salvarConcessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarConcessaoActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConcessaoLayout = new javax.swing.GroupLayout(panelConcessao);
        panelConcessao.setLayout(panelConcessaoLayout);
        panelConcessaoLayout.setHorizontalGroup(
            panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcessaoLayout.createSequentialGroup()
                .addGroup(panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(salvarConcessao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelConcessaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConcessaoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(externoRadio))
                            .addComponent(cbxArmarioConcessao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxLocalizacaoArmarioConcessao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelConcessaoLayout.createSequentialGroup()
                                .addGroup(panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLocalizacaoArmario1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblArmario1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelConcessaoLayout.setVerticalGroup(
            panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConcessaoLayout.createSequentialGroup()
                .addComponent(lblLocalizacaoArmario1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cbxLocalizacaoArmarioConcessao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblArmario1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cbxArmarioConcessao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConcessaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(externoRadio))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salvarConcessao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelGeralLayout = new javax.swing.GroupLayout(panelGeral);
        panelGeral.setLayout(panelGeralLayout);
        panelGeralLayout.setHorizontalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelConcessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelGeralLayout.setVerticalGroup(
            panelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeralLayout.createSequentialGroup()
                .addComponent(panelConcessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        fecharFormulario();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void salvarConcessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarConcessaoActionPerformed
        try {
            System.out.print(System.getProperty("user"));
            concessao.setArmario((Armario) cbxArmarioConcessao.getSelectedItem());
            concessao.setServidor(servidor);
            concessao.setDescricao(informacoes.getText());

            ConcessaoServico.inserir(concessao);
            JOptionPane.showMessageDialog(this, MensagemUtil.CONCESSAO_CONCEDIDA);
            Armario armario = ((Armario) cbxArmarioConcessao.getSelectedItem());
            armario.setStatus(StatusArmario.OCUPADO);
            ArmarioServico.atualizar(armario);
            fecharFormulario();

        } catch (ConcessaoException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, MensagemUtil.CONCESSAO_SERVIDOR_ERRO + e, MensagemUtil.TITULO_ERRO_FATAL, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_salvarConcessaoActionPerformed

    private void externoRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externoRadioActionPerformed
        informacoes.setText(" Externo Nome:  \nTelefone:\n Motivo:");
    }//GEN-LAST:event_externoRadioActionPerformed

    private void cbxArmarioConcessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxArmarioConcessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxArmarioConcessaoActionPerformed

    private void cbxLocalizacaoArmarioConcessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxLocalizacaoArmarioConcessaoActionPerformed
        Localizacao localEscolhidoConcessao = (Localizacao) cbxLocalizacaoArmarioConcessao.getSelectedItem();
        ArmarioComboBoxModel armarioComboBoxModel = ComboBoxServico.inicializaComboBoxArmarioAtivo(localEscolhidoConcessao);
        cbxArmarioConcessao.setModel(armarioComboBoxModel);
    }//GEN-LAST:event_cbxLocalizacaoArmarioConcessaoActionPerformed

    private void fecharFormulario() {
        this.indexConcessaoPanelUI.init();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxArmarioConcessao;
    private javax.swing.JComboBox<String> cbxLocalizacaoArmarioConcessao;
    private javax.swing.JRadioButton externoRadio;
    private javax.swing.JTextArea informacoes;
    private javax.swing.JButton jButton3;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArmario1;
    private javax.swing.JLabel lblLocalizacaoArmario1;
    private javax.swing.JPanel panelConcessao;
    private javax.swing.JPanel panelGeral;
    private javax.swing.JButton salvarConcessao;
    // End of variables declaration//GEN-END:variables
}
