package br.edu.ifpr.paranavai.armarios.visao.concessao;

import br.edu.ifpr.paranavai.armarios.modelo.Concessao;
import br.edu.ifpr.paranavai.armarios.servico.ConcessaoServico;

import br.edu.ifpr.paranavai.armarios.utils.OperacaoUtil;
import br.edu.ifpr.paranavai.armarios.visao.tabela.acoes.AcoesEventoTabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Allan Fernando O de Andrade
 */
public class IndexConcessaoPanelUI extends javax.swing.JPanel {

    private final int QUANTIDADE_COLUNAS = 4;

    List<Concessao> listaDeConcessoes;

    public IndexConcessaoPanelUI() {
        initComponents();
        init();
    }

    public void init() {
        listaDeConcessoes = ConcessaoServico.buscarTodos();
        populaTabela(listaDeConcessoes);
    }

    private void populaTabela(List<Concessao> lista) {

        AcoesEventoTabela evento = new AcoesEventoTabelaConcessao();

        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) tblConcessao.getModel();
        tblConcessao.getColumnModel().getColumn(7).setCellRenderer(new RenderizadorDasAcoesDaCelulaConcessao());
        tblConcessao.getColumnModel().getColumn(7).setCellEditor(new EditorDasAcoesDaCelulaTabelaConcessao(evento));
        //  Primeiro limpa a tabela
        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }

        for (int i = 0; i < lista.size(); i++) {
            Concessao mostraConcessao = lista.get(i);
            Object[] dadosLinha = new Object[7];
            dadosLinha[0] = mostraConcessao.getId();
            dadosLinha[1] = OperacaoUtil.formatarDataHora(mostraConcessao.getDataConcessao());
            dadosLinha[2] = OperacaoUtil.formatarDataHora(mostraConcessao.getDataDevolucao());
            dadosLinha[3] = mostraConcessao.getServidor().getNomeCompleto();
            dadosLinha[4] = mostraConcessao.getArmario().getNumero();
            dadosLinha[5] = mostraConcessao.getArmario().getLocalizacao().getDescricao();
            dadosLinha[6] = mostraConcessao.getDescricao();

            modeloDeColunasDaTabela.addRow(dadosLinha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelSuperior = new javax.swing.JPanel();
        panelEscolherFiltro = new javax.swing.JPanel();
        lblTipoFiltro = new javax.swing.JLabel();
        cbxFitro = new javax.swing.JComboBox<>();
        panelBusca = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConcessao = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(4, 4));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.GridLayout(1, 0));

        painelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        painelGeral.setLayout(new java.awt.BorderLayout(0, 5));

        painelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelSuperior.setLayout(new java.awt.GridLayout(3, 0));

        panelEscolherFiltro.setBackground(new java.awt.Color(255, 255, 255));
        panelEscolherFiltro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        panelEscolherFiltro.setLayout(new javax.swing.BoxLayout(panelEscolherFiltro, javax.swing.BoxLayout.LINE_AXIS));

        lblTipoFiltro.setText("Buscar por:");
        panelEscolherFiltro.add(lblTipoFiltro);

        cbxFitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Concessões Ativas", "Concessões Finalizadas", "Armário", "Data Empréstimo", "Data Devolução", "Servidor", "Localizacao", "Siape" }));
        cbxFitro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxFitroFocusLost(evt);
            }
        });
        panelEscolherFiltro.add(cbxFitro);

        painelSuperior.add(panelEscolherFiltro);

        panelBusca.setBackground(new java.awt.Color(255, 255, 255));
        panelBusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        panelBusca.setLayout(new javax.swing.BoxLayout(panelBusca, javax.swing.BoxLayout.LINE_AXIS));

        lblBusca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBusca.setText("Ativos:");
        lblBusca.setMaximumSize(new java.awt.Dimension(50, 16));
        lblBusca.setMinimumSize(new java.awt.Dimension(50, 16));
        lblBusca.setPreferredSize(new java.awt.Dimension(100, 16));
        panelBusca.add(lblBusca);

        txtBusca.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        panelBusca.add(txtBusca);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusca.add(btnBuscar);

        painelSuperior.add(panelBusca);

        panelNovo.setBackground(new java.awt.Color(255, 255, 255));
        panelNovo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelNovo.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        btnNovo.setText("Novo");
        btnNovo.setMaximumSize(new java.awt.Dimension(72, 72));
        btnNovo.setMinimumSize(new java.awt.Dimension(72, 72));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelNovo.add(btnNovo);

        painelSuperior.add(panelNovo);

        painelGeral.add(painelSuperior, java.awt.BorderLayout.PAGE_START);

        painelInferior.setBackground(new java.awt.Color(0, 153, 0));
        painelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelInferior.setLayout(new java.awt.BorderLayout());

        tblConcessao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Data Empréstimo", "Data Devolução", "Servidor", "Armário", "Localização", "Descrição", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConcessao.setRequestFocusEnabled(false);
        tblConcessao.setRowHeight(30);
        tblConcessao.setSelectionBackground(new java.awt.Color(57, 137, 111));
        tblConcessao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblConcessao);

        painelInferior.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        painelGeral.add(painelInferior, java.awt.BorderLayout.CENTER);

        add(painelGeral);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ArrayList<Concessao> filtrado = new ArrayList<>();
        String filtro = cbxFitro.getSelectedItem().toString();
        String termoDeBusca = txtBusca.getText().toUpperCase();

        switch (filtro) {
            case "Concessões Ativas":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getDataDevolucao() == null) {
                        filtrado.add(e);
                    }
                }
                break;
            case "Concessões Finalizadas":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getDataDevolucao() == null) {
                        filtrado.add(e);
                    }
                }
                break;
            case "Armário":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getArmario().getNumero().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;
            case "Data Empréstimo":
                for (Concessao e : listaDeConcessoes) {
                    if (OperacaoUtil.formatarDataHora(e.getDataConcessao()).toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;

            case "Data Devolução":
                for (Concessao e : listaDeConcessoes) {
                    if (OperacaoUtil.formatarDataHora(e.getDataDevolucao()).toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;
            case "Servidor":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getServidor().getNomeCompleto().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;
            case "Localização":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getArmario().getLocalizacao().getDescricao().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;
                 case "Siape":
                for (Concessao e : listaDeConcessoes) {
                    if (e.getServidor().getSiape().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
                break;
        }
        populaTabela(filtrado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        ConcessaoUIModal criacaoEdicaoConcessao = new ConcessaoUIModal(this);
        criacaoEdicaoConcessao.setLocationRelativeTo(this);
        criacaoEdicaoConcessao.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cbxFitroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxFitroFocusLost
        lblBusca.setText(cbxFitro.getSelectedItem().toString() + ":");
    }//GEN-LAST:event_cbxFitroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cbxFitro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTipoFiltro;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelEscolherFiltro;
    private javax.swing.JPanel panelNovo;
    private javax.swing.JTable tblConcessao;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
