package br.edu.ifpr.paranavai.armarios.visao.concessao;

import br.edu.ifpr.paranavai.armarios.modelo.Concessao;
import br.edu.ifpr.paranavai.armarios.modelo.Servidor;
import br.edu.ifpr.paranavai.armarios.utils.OperacaoUtil;
import br.edu.ifpr.paranavai.armarios.visao.servidor.VisualizarServidorModalUI;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.JPanel;

public class VisualizarConcessaoModalUI extends javax.swing.JDialog {

    Servidor servidor = new Servidor();
    JPanel frame = new JPanel();
    public VisualizarConcessaoModalUI(JPanel parent, Concessao concessao) {
        super((JFrame) SwingUtilities.getWindowAncestor(parent), true);
        initComponents();
        preencheDados(concessao);
        frame = parent;
        servidor = concessao.getServidor();
    }

    private void preencheDados(Concessao concessao) {
        campoIdentificador.setText(concessao.getId().toString());
        campoDataConcessao.setText(OperacaoUtil.formatarDataHora(concessao.getDataConcessao()));
        campoDataDevolucao.setText(OperacaoUtil.formatarDataHora(concessao.getDataDevolucao()));
        campoServidor.setText(concessao.getServidor().getNomeCompleto() + " " + concessao.getServidor().getSiape());
        campoArmario.setText(concessao.getArmario().getNumero());
        campoLocalizacao.setText(concessao.getArmario().getLocalizacao().getDescricao());
        campoDescricao.setText(concessao.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelSuperior = new javax.swing.JPanel();
        lblIdentificador = new javax.swing.JLabel();
        campoIdentificador = new javax.swing.JLabel();
        lblDataConcessao = new javax.swing.JLabel();
        campoDataConcessao = new javax.swing.JLabel();
        lblDataDevolucao = new javax.swing.JLabel();
        campoDataDevolucao = new javax.swing.JLabel();
        lblEstudante = new javax.swing.JLabel();
        campoServidor = new javax.swing.JLabel();
        lblArmario = new javax.swing.JLabel();
        campoArmario = new javax.swing.JLabel();
        lblLocalizacao = new javax.swing.JLabel();
        campoLocalizacao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        campoDescricao = new javax.swing.JLabel();
        visualizaAluno = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro Acadêmico");
        setBackground(new java.awt.Color(0, 153, 0));
        setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        panelSuperior.setBackground(new java.awt.Color(255, 255, 255));
        panelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Concessão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelSuperior.setMinimumSize(new java.awt.Dimension(100, 100));

        lblIdentificador.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIdentificador.setText("Identificador:");

        campoIdentificador.setText("...");

        lblDataConcessao.setText("Data Concessão:");

        campoDataConcessao.setText("...");

        lblDataDevolucao.setText("Data Devolução:");

        campoDataDevolucao.setText("...");

        lblEstudante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstudante.setText("Servidor:");

        campoServidor.setText("...");

        lblArmario.setText("Armário:");

        campoArmario.setText("...");

        lblLocalizacao.setText("Localização:");
        lblLocalizacao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        campoLocalizacao.setText("...");

        jLabel1.setText("Descrição:");

        campoDescricao.setText("...");
        campoDescricao.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        visualizaAluno.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        visualizaAluno.setText("INFO");
        visualizaAluno.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/visualizar-16.png"))); // NOI18N
        visualizaAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visualizaAlunoMouseClicked(evt);
            }
        });
        visualizaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizaAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSuperiorLayout = new javax.swing.GroupLayout(panelSuperior);
        panelSuperior.setLayout(panelSuperiorLayout);
        panelSuperiorLayout.setHorizontalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDataDevolucao)
                    .addComponent(lblIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(visualizaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblEstudante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblArmario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblLocalizacao)
                    .addComponent(lblDataConcessao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoDataDevolucao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoServidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoArmario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoDataConcessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoIdentificador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorLayout.createSequentialGroup()
                        .addComponent(campoLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelSuperiorLayout.createSequentialGroup()
                        .addComponent(campoDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelSuperiorLayout.setVerticalGroup(
            panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorLayout.createSequentialGroup()
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificador)
                    .addComponent(campoIdentificador))
                .addGap(4, 4, 4)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataConcessao)
                    .addComponent(campoDataConcessao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataDevolucao)
                    .addComponent(campoDataDevolucao))
                .addGap(5, 5, 5)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudante)
                    .addComponent(campoServidor)
                    .addComponent(visualizaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArmario)
                    .addComponent(campoArmario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoLocalizacao)
                    .addComponent(lblLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(campoDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/IfLogo_dark.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizaAlunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visualizaAlunoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_visualizaAlunoMouseClicked

    private void visualizaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizaAlunoActionPerformed

        VisualizarServidorModalUI form = new VisualizarServidorModalUI(frame, servidor);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
    }//GEN-LAST:event_visualizaAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel campoArmario;
    private javax.swing.JLabel campoDataConcessao;
    private javax.swing.JLabel campoDataDevolucao;
    private javax.swing.JLabel campoDescricao;
    private javax.swing.JLabel campoIdentificador;
    private javax.swing.JLabel campoLocalizacao;
    private javax.swing.JLabel campoServidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArmario;
    private javax.swing.JLabel lblDataConcessao;
    private javax.swing.JLabel lblDataDevolucao;
    private javax.swing.JLabel lblEstudante;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblLocalizacao;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JButton visualizaAluno;
    // End of variables declaration//GEN-END:variables
}
