package br.edu.ifpr.paranavai.armarios.visao;

import br.edu.ifpr.paranavai.armarios.excecoes.LoginException;
import br.edu.ifpr.paranavai.armarios.modelo.Estudante;
import br.edu.ifpr.paranavai.armarios.servico.EmprestimoServico;
import br.edu.ifpr.paranavai.armarios.servico.LoginServico;
import br.edu.ifpr.paranavai.armarios.utils.MensagemUtil;
import br.edu.ifpr.paranavai.armarios.visao.estudante.EstudantesDevolucaoUI;
import br.edu.ifpr.paranavai.armarios.visao.estudante.EstudantesEmprestimoUI;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Marcelo Figueiredo Terenciani
 */
public class EmprestimoEstudanteUI extends javax.swing.JFrame {

    /**
     * Creates new form LoginEstudanteNovo
     */
    public EmprestimoEstudanteUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConteudo = new JPanel() {
            public void paintComponent(Graphics g) {
                Image img = Toolkit.getDefaultToolkit().getImage(
                    IndexLoginUI.class.getResource("/assets/imgindex.png"));
                g.drawImage(img, 0, 0, this.getWidth(), this.getHeight(), this);
            }
        };
        lblTituloSistema = new javax.swing.JLabel();
        lblIconeIFPR = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        painelBorda = new javax.swing.JPanel();
        painelLogin = new javax.swing.JPanel();
        lblRa = new javax.swing.JLabel();
        txtRa = new javax.swing.JTextField();
        lblErroRa = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblErroSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setUndecorated(true);
        setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize()));

        painelConteudo.setBackground(new java.awt.Color(0, 153, 0));
        painelConteudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        painelConteudo.setForeground(new java.awt.Color(255, 255, 255));
        painelConteudo.setLayout(new java.awt.BorderLayout());

        lblTituloSistema.setFont(new java.awt.Font("SansSerif", 0, 48)); // NOI18N
        lblTituloSistema.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloSistema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloSistema.setText(MensagemUtil.TITULO_SISTEMA);
        lblTituloSistema.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 10, 1));
        painelConteudo.add(lblTituloSistema, java.awt.BorderLayout.PAGE_START);

        lblIconeIFPR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeIFPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iflogomenor.png"))); // NOI18N
        painelConteudo.add(lblIconeIFPR, java.awt.BorderLayout.PAGE_END);

        painelCentral.setOpaque(false);

        painelBorda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        painelBorda.setMinimumSize(new java.awt.Dimension(500, 500));
        painelBorda.setPreferredSize(new java.awt.Dimension(400, 450));
        painelBorda.setLayout(new java.awt.GridLayout(1, 1));

        painelLogin.setBackground(new java.awt.Color(0, 153, 0));
        painelLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        painelLogin.setLayout(new java.awt.GridLayout(7, 1, 0, 5));

        lblRa.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        lblRa.setForeground(new java.awt.Color(255, 255, 255));
        lblRa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRa.setText("Matrícula (RA)");
        lblRa.setMaximumSize(new java.awt.Dimension(300, 54));
        lblRa.setMinimumSize(new java.awt.Dimension(300, 54));
        lblRa.setPreferredSize(new java.awt.Dimension(300, 54));
        painelLogin.add(lblRa);

        txtRa.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtRa.setMinimumSize(new java.awt.Dimension(100, 54));
        txtRa.setPreferredSize(new java.awt.Dimension(100, 54));
        painelLogin.add(txtRa);

        lblErroRa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        painelLogin.add(lblErroRa);

        lblSenha.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("Senha");
        painelLogin.add(lblSenha);

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        painelLogin.add(txtSenha);

        lblErroSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblErroSenha.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        painelLogin.add(lblErroSenha);

        btnEntrar.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        btnEntrar.setText("EMPRESTAR / DEVOLVER");
        btnEntrar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        painelLogin.add(btnEntrar);

        painelBorda.add(painelLogin);

        painelCentral.add(painelBorda);

        painelConteudo.add(painelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        try {
            String ra = this.txtRa.getText();
            char[] caracteresSenha = this.txtSenha.getPassword();
            String senha = new String(caracteresSenha);
            Estudante estudante = LoginServico.verificaEstudante(ra, senha);
            txtSenha.setText("");
            txtRa.setText("");

            if (EmprestimoServico.buscarAtivoPorRaDoEstudante(estudante.getRa()) == null) {
                System.setProperty("ra", estudante.getRa());
                EstudantesEmprestimoUI estudanteEmprestimoUI = new EstudantesEmprestimoUI(this);
                estudanteEmprestimoUI.setLocationRelativeTo(this);
                estudanteEmprestimoUI.setVisible(true);

            } else {
                System.setProperty("ra", estudante.getRa());
                EstudantesDevolucaoUI estudanteDevolucaoUUI = new EstudantesDevolucaoUI(this);
                estudanteDevolucaoUUI.setVisible(true);
            }
        } catch (LoginException e) {
            // TODO resposta joptionpane
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmprestimoEstudanteUI.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmprestimoEstudanteUI.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmprestimoEstudanteUI.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmprestimoEstudanteUI.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmprestimoEstudanteUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnEntrar;
    private javax.swing.JLabel lblErroRa;
    private javax.swing.JLabel lblErroSenha;
    private javax.swing.JLabel lblIconeIFPR;
    private javax.swing.JLabel lblRa;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTituloSistema;
    private javax.swing.JPanel painelBorda;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelConteudo;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JTextField txtRa;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
