/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifpr.paranavai.armarios.visao;

/**
 *
 * @author BAEZ
 */
public class InicioPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form InicioPrincipal
     */
    public InicioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblArmariosDisponveis = new javax.swing.JLabel();
        txtArmariosDisponiveis = new javax.swing.JTextField();
        lblArmariosOcupados = new javax.swing.JLabel();
        txtArmariosOcupados = new javax.swing.JTextField();
        lblEstudantesAtivos = new javax.swing.JLabel();
        txtEstudantesAtivos = new javax.swing.JTextField();
        lblArmariosInativados = new javax.swing.JLabel();
        txtArmariosInativados = new javax.swing.JTextField();
        btnAbrirSistemaEmprestimo = new javax.swing.JPanel();
        imgAbrirSistemaEmprestimo = new javax.swing.JLabel();
        lblAbrirSistemaEmprestimo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 153));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblArmariosDisponveis.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblArmariosDisponveis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArmariosDisponveis.setText("Armários Disponíveis");

        txtArmariosDisponiveis.setEditable(false);
        txtArmariosDisponiveis.setBackground(new java.awt.Color(204, 204, 204));
        txtArmariosDisponiveis.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtArmariosDisponiveis.setForeground(new java.awt.Color(255, 0, 51));
        txtArmariosDisponiveis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArmariosDisponiveis.setText("Saldo");
        txtArmariosDisponiveis.setBorder(null);

        lblArmariosOcupados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblArmariosOcupados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArmariosOcupados.setText("Armários Ocupados");

        txtArmariosOcupados.setEditable(false);
        txtArmariosOcupados.setBackground(new java.awt.Color(204, 204, 204));
        txtArmariosOcupados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtArmariosOcupados.setForeground(new java.awt.Color(255, 0, 51));
        txtArmariosOcupados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArmariosOcupados.setText("Saldo");
        txtArmariosOcupados.setBorder(null);

        lblEstudantesAtivos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEstudantesAtivos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstudantesAtivos.setText("Estudantes Ativos");

        txtEstudantesAtivos.setEditable(false);
        txtEstudantesAtivos.setBackground(new java.awt.Color(204, 204, 204));
        txtEstudantesAtivos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtEstudantesAtivos.setForeground(new java.awt.Color(255, 0, 51));
        txtEstudantesAtivos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstudantesAtivos.setText("Saldo");
        txtEstudantesAtivos.setBorder(null);

        lblArmariosInativados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblArmariosInativados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblArmariosInativados.setText("Armários Inativados");

        txtArmariosInativados.setEditable(false);
        txtArmariosInativados.setBackground(new java.awt.Color(204, 204, 204));
        txtArmariosInativados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtArmariosInativados.setForeground(new java.awt.Color(255, 0, 51));
        txtArmariosInativados.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtArmariosInativados.setText("Saldo");
        txtArmariosInativados.setBorder(null);
        txtArmariosInativados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArmariosInativadosActionPerformed(evt);
            }
        });

        btnAbrirSistemaEmprestimo.setBackground(new java.awt.Color(8, 166, 97));
        btnAbrirSistemaEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAbrirSistemaEmprestimoMousePressed(evt);
            }
        });

        imgAbrirSistemaEmprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/painelcontrole/abrir-branco-64px.png"))); // NOI18N

        lblAbrirSistemaEmprestimo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAbrirSistemaEmprestimo.setForeground(new java.awt.Color(255, 255, 255));
        lblAbrirSistemaEmprestimo.setText("Abrir Sistema de Empréstimos");

        javax.swing.GroupLayout btnAbrirSistemaEmprestimoLayout = new javax.swing.GroupLayout(btnAbrirSistemaEmprestimo);
        btnAbrirSistemaEmprestimo.setLayout(btnAbrirSistemaEmprestimoLayout);
        btnAbrirSistemaEmprestimoLayout.setHorizontalGroup(
            btnAbrirSistemaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAbrirSistemaEmprestimoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgAbrirSistemaEmprestimo)
                .addGap(20, 20, 20)
                .addComponent(lblAbrirSistemaEmprestimo)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        btnAbrirSistemaEmprestimoLayout.setVerticalGroup(
            btnAbrirSistemaEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgAbrirSistemaEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addComponent(lblAbrirSistemaEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtArmariosDisponiveis)
                    .addComponent(lblArmariosDisponveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEstudantesAtivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEstudantesAtivos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblArmariosOcupados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblArmariosInativados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtArmariosOcupados)
                    .addComponent(txtArmariosInativados, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAbrirSistemaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblArmariosOcupados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArmariosDisponveis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArmariosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArmariosOcupados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstudantesAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArmariosInativados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstudantesAtivos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtArmariosInativados, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnAbrirSistemaEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtArmariosInativadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArmariosInativadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtArmariosInativadosActionPerformed

    private void btnAbrirSistemaEmprestimoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbrirSistemaEmprestimoMousePressed
        LoginEstudanteUI loginEstudanteUI = new LoginEstudanteUI();
        loginEstudanteUI.setVisible(true);
    }//GEN-LAST:event_btnAbrirSistemaEmprestimoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAbrirSistemaEmprestimo;
    private javax.swing.JLabel imgAbrirSistemaEmprestimo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAbrirSistemaEmprestimo;
    private javax.swing.JLabel lblArmariosDisponveis;
    private javax.swing.JLabel lblArmariosInativados;
    private javax.swing.JLabel lblArmariosOcupados;
    private javax.swing.JLabel lblEstudantesAtivos;
    private javax.swing.JTextField txtArmariosDisponiveis;
    private javax.swing.JTextField txtArmariosInativados;
    private javax.swing.JTextField txtArmariosOcupados;
    private javax.swing.JTextField txtEstudantesAtivos;
    // End of variables declaration//GEN-END:variables
}
