/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.paranavai.armarios.visao;

import br.edu.ifpr.paranavai.armarios.modelo.Estudante;
import br.edu.ifpr.paranavai.armarios.modelo.ReservaBiblioteca;
import br.edu.ifpr.paranavai.armarios.modelo.ReservaSaguao;
import br.edu.ifpr.paranavai.armarios.servico.ReservaBibliotecaServico;
import br.edu.ifpr.paranavai.armarios.servico.ReservaSaguaoServico;
import java.util.List;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author suporte
 */
public class ListaArmarioUI extends javax.swing.JFrame {

    /**
     * Creates new form ListaArmarioUI
     */
    public ListaArmarioUI() {

        initComponents();
        setLocationRelativeTo(null);
        
        List<ReservaSaguao> armariosSaguao = ReservaSaguaoServico.buscarTodos();
        populaTabelaSaguao(armariosSaguao);

        List<ReservaBiblioteca> armarioBiblioteca = ReservaBibliotecaServico.buscarTodos();
        populaTabela(armarioBiblioteca);

        
    }
    // </editor-fold>
    Estudante estudante = new Estudante();

    @SuppressWarnings("unchecked")
    private void populaTabela(List<ReservaBiblioteca> reservas) {
        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) tableBiblioteca.getModel();
        //  Primeiro limpa a tabela
        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }
        

        for (int i = 0; i < reservas.size(); i++) {
            ReservaBiblioteca reserva = reservas.get(i);
            if (reserva.getEstudante() == null) {
                estudante.setNome("Disponível");
                reserva.setEstudante(estudante);

                Object[] dadosLinha = new Object[4];
                dadosLinha[0] = reserva.getNumero();
                dadosLinha[1] = reserva.getEstudante().getNome();
                dadosLinha[2] = reserva.getDataHoraEmprestimo();
                dadosLinha[3] = !reserva.isAtivo();

                modeloDeColunasDaTabela.addRow(dadosLinha);
            } else {

                Object[] dadosLinha = new Object[4];
                dadosLinha[0] = reserva.getNumero();
                dadosLinha[1] = reserva.getEstudante().getNome();
                dadosLinha[2] = reserva.getDataHoraEmprestimo();
                dadosLinha[3] = !reserva.isAtivo();
                modeloDeColunasDaTabela.addRow(dadosLinha);

            }
        }
    }

    @SuppressWarnings("unchecked")
    private void populaTabelaSaguao(List<ReservaSaguao> reservasS) {
        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) tableSaguao.getModel();
        //  Primeiro limpa a tabela
        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }
       

        for (int i = 0; i < reservasS.size(); i++) {
            ReservaSaguao reservaSS = reservasS.get(i);
            if (reservaSS.getEstudante() == null) {
                estudante.setNome("Disponível");
                reservaSS.setEstudante(estudante);
                Object[] dadosLinha = new Object[4];
                dadosLinha[0] = reservaSS.getNumero();
                dadosLinha[1] = reservaSS.getEstudante().getNome();
                dadosLinha[2] = reservaSS.getDataHoraEmprestimo();
                dadosLinha[3] = !reservaSS.isAtivo();

                modeloDeColunasDaTabela.addRow(dadosLinha);
            } else {
            Object[] dadosLinha = new Object[4];
            dadosLinha[0] = reservaSS.getNumero();
            dadosLinha[1] = reservaSS.getEstudante().getNome();
            dadosLinha[2] = reservaSS.getDataHoraEmprestimo();
            dadosLinha[3] = !reservaSS.isAtivo();

            modeloDeColunasDaTabela.addRow(dadosLinha);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSeparator1 = new javax.swing.JSeparator();
        cor = new javax.swing.JPanel();
        geral = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBiblioteca = new javax.swing.JTable();
        desativaBiblioteca = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableSaguao = new javax.swing.JTable();
        desativaSaguao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        cor.setBackground(new java.awt.Color(0, 153, 0));
        cor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biblioteca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tableBiblioteca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Aluno", "Data", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Short.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBiblioteca.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableBiblioteca);

        desativaBiblioteca.setText("Desativar");
        desativaBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desativaBibliotecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(desativaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desativaBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout geralLayout = new javax.swing.GroupLayout(geral);
        geral.setLayout(geralLayout);
        geralLayout.setHorizontalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        geralLayout.setVerticalGroup(
            geralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saguão", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tableSaguao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Aluno", "Data", "Ativo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Short.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableSaguao);

        desativaSaguao.setText("Desativar");
        desativaSaguao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desativaSaguaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(desativaSaguao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desativaSaguao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout corLayout = new javax.swing.GroupLayout(cor);
        cor.setLayout(corLayout);
        corLayout.setHorizontalGroup(
            corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, corLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        corLayout.setVerticalGroup(
            corLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(corLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 431;
        gridBagConstraints.ipady = 172;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 12);
        getContentPane().add(cor, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void desativaSaguaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desativaSaguaoActionPerformed
        int dadosLinha = tableSaguao.getSelectedRow();
        int codigo = (int) tableSaguao.getModel().getValueAt(dadosLinha, 0);
        String status = (String) tableSaguao.getModel().getValueAt(dadosLinha, 1);
        if(status.equals("Disponível")){
            ReservaSaguaoServico.apagaPorNumero(codigo);
            List<ReservaSaguao> armarioSaguao = ReservaSaguaoServico.buscarTodos();
            populaTabelaSaguao(armarioSaguao);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Armário em uso, impossível deletar");
        }
    }//GEN-LAST:event_desativaSaguaoActionPerformed

    private void desativaBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desativaBibliotecaActionPerformed
        int dadosLinha = tableBiblioteca.getSelectedRow();
        int codigo = (int) tableBiblioteca.getModel().getValueAt(dadosLinha, 0);
        String status = (String) tableBiblioteca.getModel().getValueAt(dadosLinha, 1);
        if(status.equals("Disponível")){
            ReservaBibliotecaServico.apagaPorNumero(codigo);
            List<ReservaBiblioteca> armarioBiblioteca = ReservaBibliotecaServico.buscarTodos();
            populaTabela(armarioBiblioteca);
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Armário em uso, impossível deletar");
           
        }
    }//GEN-LAST:event_desativaBibliotecaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void listaArmarioUI(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaArmarioUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaArmarioUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaArmarioUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaArmarioUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaArmarioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cor;
    private javax.swing.JButton desativaBiblioteca;
    private javax.swing.JButton desativaSaguao;
    private javax.swing.JPanel geral;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableBiblioteca;
    private javax.swing.JTable tableSaguao;
    // End of variables declaration//GEN-END:variables
}
