package br.edu.ifpr.paranavai.armarios.visao;

import br.edu.ifpr.paranavai.armarios.modelo.Localizacao;
import br.edu.ifpr.paranavai.armarios.servico.ComboBoxServico;
import br.edu.ifpr.paranavai.armarios.visao.combobox.LocalizacaoComboBoxModel;

/**
 *
 * @author prof Marcelo F. Terenciani
 */
public class SelecionarLocalizacaoUI extends javax.swing.JDialog {

    private PainelDeControle painelDeControle;

    /**
     * Creates new form SelecionarLocalizacaoUI
     *
     * @param painelDeControle
     */
    public SelecionarLocalizacaoUI(PainelDeControle painelDeControle) {
        super(painelDeControle, true);
        initComponents();
        this.painelDeControle = painelDeControle;
        this.setLocationRelativeTo(painelDeControle);
        LocalizacaoComboBoxModel localizacaoComboBoxModel = ComboBoxServico.inicializaComboBoxLocalizacao();
        cbxLocalizacao.setModel(localizacaoComboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelConteudo = new javax.swing.JPanel();
        lblIconeIFPR = new javax.swing.JLabel();
        painelCentral = new javax.swing.JPanel();
        lblSelecionarLocalizacao = new javax.swing.JLabel();
        lblSelecionarLocalizacao1 = new javax.swing.JLabel();
        cbxLocalizacao = new javax.swing.JComboBox<>();
        btnDefinirLocalizacao = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 350));

        painelConteudo.setBackground(new java.awt.Color(0, 153, 0));
        painelConteudo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        painelConteudo.setForeground(new java.awt.Color(255, 255, 255));
        painelConteudo.setMinimumSize(new java.awt.Dimension(500, 350));
        painelConteudo.setPreferredSize(new java.awt.Dimension(500, 350));
        painelConteudo.setLayout(new java.awt.BorderLayout());

        lblIconeIFPR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconeIFPR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/iflogomenor.png"))); // NOI18N
        painelConteudo.add(lblIconeIFPR, java.awt.BorderLayout.PAGE_END);

        painelCentral.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));
        painelCentral.setMinimumSize(new java.awt.Dimension(500, 350));
        painelCentral.setOpaque(false);
        painelCentral.setPreferredSize(new java.awt.Dimension(500, 350));
        painelCentral.setLayout(new java.awt.GridLayout(4, 0, 0, 10));

        lblSelecionarLocalizacao.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        lblSelecionarLocalizacao.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecionarLocalizacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelecionarLocalizacao.setText("Informe a localização dos armários");
        lblSelecionarLocalizacao.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSelecionarLocalizacao.setMaximumSize(new java.awt.Dimension(300, 54));
        lblSelecionarLocalizacao.setMinimumSize(new java.awt.Dimension(300, 54));
        lblSelecionarLocalizacao.setPreferredSize(new java.awt.Dimension(300, 54));
        painelCentral.add(lblSelecionarLocalizacao);

        lblSelecionarLocalizacao1.setFont(new java.awt.Font("Source Sans Pro Black", 0, 24)); // NOI18N
        lblSelecionarLocalizacao1.setForeground(new java.awt.Color(255, 255, 255));
        lblSelecionarLocalizacao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelecionarLocalizacao1.setText("que este terminal irá gerenciar");
        lblSelecionarLocalizacao1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblSelecionarLocalizacao1.setMaximumSize(new java.awt.Dimension(300, 54));
        lblSelecionarLocalizacao1.setMinimumSize(new java.awt.Dimension(300, 54));
        lblSelecionarLocalizacao1.setPreferredSize(new java.awt.Dimension(300, 54));
        painelCentral.add(lblSelecionarLocalizacao1);

        cbxLocalizacao.setSelectedItem(1);
        painelCentral.add(cbxLocalizacao);

        btnDefinirLocalizacao.setFont(new java.awt.Font("Source Code Pro Black", 0, 24)); // NOI18N
        btnDefinirLocalizacao.setText("CONFIRMAR");
        btnDefinirLocalizacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 0))); // NOI18N
        btnDefinirLocalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDefinirLocalizacaoActionPerformed(evt);
            }
        });
        painelCentral.add(btnDefinirLocalizacao);

        painelConteudo.add(painelCentral, java.awt.BorderLayout.CENTER);

        getContentPane().add(painelConteudo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fecharFormulario() {
        this.painelDeControle.dispose();
        this.dispose();
    }

    private void btnDefinirLocalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDefinirLocalizacaoActionPerformed
        Localizacao localizacao = (Localizacao) cbxLocalizacao.getSelectedItem();
        EmprestimoEstudanteUI loginEstudanteUI = new EmprestimoEstudanteUI(localizacao);
        loginEstudanteUI.setVisible(true);
        this.fecharFormulario();
    }//GEN-LAST:event_btnDefinirLocalizacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDefinirLocalizacao;
    private javax.swing.JComboBox<String> cbxLocalizacao;
    private javax.swing.JLabel lblIconeIFPR;
    private javax.swing.JLabel lblSelecionarLocalizacao;
    private javax.swing.JLabel lblSelecionarLocalizacao1;
    private javax.swing.JPanel painelCentral;
    private javax.swing.JPanel painelConteudo;
    // End of variables declaration//GEN-END:variables
}
