package br.edu.ifpr.paranavai.armarios.visao.emprestimo;

import br.edu.ifpr.paranavai.armarios.modelo.Emprestimo;
import br.edu.ifpr.paranavai.armarios.servico.EmprestimoServico;
import br.edu.ifpr.paranavai.armarios.utils.OperacaoUtil;
import br.edu.ifpr.paranavai.armarios.visao.tabela.acoes.AcoesEventoTabela;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author professor Marcelo F. Terenciani
 */
public class IndexEmprestimoPanelUI extends javax.swing.JPanel {

    private final int QUANTIDADE_COLUNAS = 4;

    List<Emprestimo> listaDeEmprestimos;

    public IndexEmprestimoPanelUI() {
        initComponents();
        init();
    }

    public void init() {
        listaDeEmprestimos = EmprestimoServico.buscarTodos();
        populaTabela(listaDeEmprestimos);
    }

    private void populaTabela(List<Emprestimo> lista) {

        AcoesEventoTabela evento = new AcoesEventoTabelaEmprestimo();

        DefaultTableModel modeloDeColunasDaTabela = (DefaultTableModel) tblEmprestimo.getModel();
        tblEmprestimo.getColumnModel().getColumn(QUANTIDADE_COLUNAS - 1).setCellRenderer(new RenderizadorDasAcoesDaCelulaEmprestimo());
        tblEmprestimo.getColumnModel().getColumn(QUANTIDADE_COLUNAS - 1).setCellEditor(new EditorDasAcoesDaCelulaTabelaEmprestimo(evento));
        //  Primeiro limpa a tabela
        while (modeloDeColunasDaTabela.getRowCount() != 0) {
            modeloDeColunasDaTabela.removeRow(0);
        }

        for (int i = 0; i < lista.size(); i++) {
            Emprestimo mostraEmprestimo = lista.get(i);
            Object[] dadosLinha = new Object[QUANTIDADE_COLUNAS];
            dadosLinha[0] = mostraEmprestimo.getId();
            dadosLinha[1] = OperacaoUtil.formatarDataHora(mostraEmprestimo.getDataEmprestimo());
            dadosLinha[2] = OperacaoUtil.formatarDataHora(mostraEmprestimo.getDataDevolucao());
            dadosLinha[3] = mostraEmprestimo.getEstudante().getNomeCompleto();
            dadosLinha[4] = mostraEmprestimo.getArmario().getNumero();
            dadosLinha[5] = mostraEmprestimo.getArmario().getLocalizacao().getDescricao();

            modeloDeColunasDaTabela.addRow(dadosLinha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelGeral = new javax.swing.JPanel();
        painelSuperior = new javax.swing.JPanel();
        panelEscolherFiltro = new javax.swing.JPanel();
        lblTipoFiltro = new javax.swing.JLabel();
        cbxFitro = new javax.swing.JComboBox<>();
        panelBusca = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        panelNovo = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        painelInferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimo = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(4, 4));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.GridLayout(1, 0));

        painelGeral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        painelGeral.setLayout(new java.awt.BorderLayout(0, 5));

        painelSuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelSuperior.setLayout(new java.awt.GridLayout(3, 0));

        panelEscolherFiltro.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        panelEscolherFiltro.setLayout(new javax.swing.BoxLayout(panelEscolherFiltro, javax.swing.BoxLayout.LINE_AXIS));

        lblTipoFiltro.setText("Buscar por:");
        panelEscolherFiltro.add(lblTipoFiltro);

        cbxFitro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativos", "Curso", "Data Empréstimo", "Data Devolução", "Estudante", "Localizacao", " " }));
        cbxFitro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbxFitroFocusLost(evt);
            }
        });
        panelEscolherFiltro.add(cbxFitro);

        painelSuperior.add(panelEscolherFiltro);

        panelBusca.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        panelBusca.setLayout(new javax.swing.BoxLayout(panelBusca, javax.swing.BoxLayout.LINE_AXIS));

        lblBusca.setText("Ativos:");
        lblBusca.setMaximumSize(new java.awt.Dimension(50, 16));
        lblBusca.setMinimumSize(new java.awt.Dimension(50, 16));
        lblBusca.setPreferredSize(new java.awt.Dimension(50, 16));
        panelBusca.add(lblBusca);

        txtBusca.setSelectedTextColor(new java.awt.Color(204, 204, 204));
        panelBusca.add(txtBusca);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusca.add(btnBuscar);

        painelSuperior.add(panelBusca);

        panelNovo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        panelNovo.setLayout(new java.awt.GridLayout(1, 3, 10, 0));

        btnNovo.setText("Novo");
        btnNovo.setMaximumSize(new java.awt.Dimension(72, 72));
        btnNovo.setMinimumSize(new java.awt.Dimension(72, 72));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panelNovo.add(btnNovo);

        painelSuperior.add(panelNovo);

        painelGeral.add(painelSuperior, java.awt.BorderLayout.PAGE_START);

        painelInferior.setBackground(new java.awt.Color(0, 153, 0));
        painelInferior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0), 6));
        painelInferior.setLayout(new java.awt.BorderLayout());

        tblEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Data Empréstimo", "Data Devolução", "Estudante", "Armário", "Localiação", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmprestimo.setRowHeight(30);
        tblEmprestimo.setSelectionBackground(new java.awt.Color(57, 137, 111));
        tblEmprestimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEmprestimo);

        painelInferior.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        painelGeral.add(painelInferior, java.awt.BorderLayout.CENTER);

        add(painelGeral);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ArrayList<Emprestimo> filtrado = new ArrayList<>();
        String filtro = cbxFitro.getSelectedItem().toString();
        String termoDeBusca = txtBusca.getText().toUpperCase();
        
        switch (filtro) {
            case "Ativos":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (e.getDataDevolucao() == null) {
                        filtrado.add(e);
                    }
                }
            case "Curso":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (e.getEstudante().getCurso().getNome().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
            case "Data Empréstimo":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (OperacaoUtil.formatarDataHora(e.getDataEmprestimo()).toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
            case "Data Devolução":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (OperacaoUtil.formatarDataHora(e.getDataDevolucao()).toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
            case "Estudante":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (e.getEstudante().getNomeCompleto().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
            case "Localização":
                for (Emprestimo e : listaDeEmprestimos) {
                    if (e.getArmario().getLocalizacao().getDescricao().toUpperCase().contains(termoDeBusca)) {
                        filtrado.add(e);
                    }
                }
            break;
        }
        populaTabela(filtrado);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        EmprestimoUIModal criacaoEdicaoEmprestimo = new EmprestimoUIModal(this);
        criacaoEdicaoEmprestimo.setLocationRelativeTo(this);
        criacaoEdicaoEmprestimo.setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void cbxFitroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbxFitroFocusLost
        lblBusca.setText(cbxFitro.getSelectedItem().toString() + ":");
    }//GEN-LAST:event_cbxFitroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox<String> cbxFitro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblTipoFiltro;
    private javax.swing.JPanel painelGeral;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JPanel panelBusca;
    private javax.swing.JPanel panelEscolherFiltro;
    private javax.swing.JPanel panelNovo;
    private javax.swing.JTable tblEmprestimo;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
