package br.edu.ifpr.paranavai.armarios.visao.utils;

/**
 *
 * @author Ifpr
 */
public class Carregando extends javax.swing.JDialog {

    /**
     * Creates new form Carregando
     *
     * @param parent
     */
    public Carregando(java.awt.Frame parent) {
        super(parent, false);
        this.setLocationRelativeTo(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gifCarregando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(100, 100));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 100));
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        gifCarregando.setBackground(new java.awt.Color(255, 255, 255));
        gifCarregando.setForeground(new java.awt.Color(255, 255, 255));
        gifCarregando.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gifCarregando.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/loading100px.gif"))); // NOI18N
        gifCarregando.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gifCarregando.setOpaque(true);
        getContentPane().add(gifCarregando);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gifCarregando;
    // End of variables declaration//GEN-END:variables
}
